### ISSUE TITLE
צריך לתקן את הבאג שנותן לנצח בשלבים למרות שנגמר הזמן

### ISSUE THREAD

**Issue by Maor-Or** [game-devcourse/Parashat_Hashavua#1]
בשלב שצריך לאכול 7 פרות, גם לאחר שהזמן נגמר היה אפשר להמשיך לשחק ואז לאכול את כל 7 הפרות ולנצח, למרות שנגמר הזמן.

גם בשלב שבו צריך לרוץ למלך פרעה דרך המבוך, במקום ללחוץ על אישור ההודעה שאומרת לי שאני צריך להתחיל לרוץ, לא עשיתי אישור ואז הטיימר לא התחיל בכלל, ויכלתי לעבור את השלב בקלות

**Comment by HadarBitan** [comment]
Got fixed.
