### ISSUE TITLE
הטקסט מופיע לאט מדי

### ISSUE THREAD

**Issue by erelsgl** [game-devcourse/Parashat_Hashavua#19]
כשהטקסט מופיע אות אחר אות, ב"אפקט מכונת כתיבה", זה מאד איטי, וגורם לי כשחקן ללחוץ על רווח שוב ושוב כדי להתקדם, אבל אז אני עלול להפסיד את סוף הטקסט.
תשקלו לוותר על האפקט הזה, ופשוט להציג את הטקסט כולו בבת אחת. לדעתי זה יקל על השחקן.

**Comment by HadarBitan** [comment]
האפקט בוטל.
