### ISSUE TITLE
לחיצה רציפה + הכתב על המגילה + אחרי הדיבור עם פרועה המשחק יוצא 

### ISSUE THREAD

**Issue by ohadtaizi** [game-devcourse/Parashat_Hashavua#4]
מה שמקשה לעשות את המשימות זה שאין לחיצה רציפה על החצים .
הדיבור עם פרועה יוצא מחוץ לגבולות של המגילה .
אחרי שמסיימים את פרשת מקץ זה יוצא מהמשחק .
אם נכשלים בהליכה בתוך המבוך הוא מחזיר לתחילת המשחק אבל גם משימות שקיבלתי עליהם מטבעות הוא מחזיר אותי לעשות .

**Comment by HadarBitan** [comment]
סודר הכול.
